// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_from_url.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedID = `-- name: GetFeedID :one
SELECT id FROM feeds WHERE url = $1
`

func (q *Queries) GetFeedID(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getFeedID, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
