// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: username_from_ID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUsername = `-- name: GetUsername :one
SELECT name FROM users WHERE id = $1
`

func (q *Queries) GetUsername(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUsername, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
